---
title: "OS: scRNAseq from external set"
author: "by Alex"
output: 
  html_document:
  toc: TRUE
toc_float: FALSE
editor_options: 
  chunk_output_type: console
---
  
  
  <style type="text/css">
  .main-container {
    max-width: 1800px;
    margin-left: 20px;
    margin-right: auto;
  }
.toc-content {
  max-width: 1800px;
  margin-left: 50px;
  margin-right: auto;
}

div {
  
  margin-left: 20px;
}


hr.new1 {
  border-top: 1px solid #84a8e0;
}



</style>
  
  # Results {.tabset}
  
  
  <div style="background-color: #f0f5c1;">
  
  
  </div>
  
  <hr>
  
  
  
```{r setup, include=FALSE, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, include = FALSE , cache.lazy = FALSE )

library ( dplyr)
library(scales)
library("RColorBrewer")
library("ggplot2")
library(gplots)
library(ggrepel)
library(Hmisc)
library(stringr)
library(gridExtra)
library(knitr)
library(kableExtra)
library ( openxlsx)
library ( ggbeeswarm )
library(Seurat)
library ( HGNChelper )

lapply(c("ggraph","igraph","tidyverse", "data.tree"), library, character.only = T)



options(scipen=999)
getPalette = colorRampPalette(brewer.pal(9, "Set1")) # expand color pallete
source ( "accessory.R")

```


```{r}

# after preprocessing and merging will be stored here
preprocessed_dir = "/projects/lab.mis/ASC_projects/scRNAseq_zhou_etal/pre_processed/"
dir.create ( preprocessed_dir )
filename = paste0(preprocessed_dir, "zhou_OS.rds" )

normalizeded_dir = "/projects/lab.mis/ASC_projects/scRNAseq_zhou_etal/normalized/"
dir.create ( normalizeded_dir )
filename_norm = paste0(normalizeded_dir, "zhou_OS.rds" )




# there are 5 samples 
raw_dir = "/projects/lab.mis/ASC_projects/scRNAseq_zhou_etal/raw/GSE152048/suppl/"
samples = list.files(raw_dir)
samples = samples[ grepl ( "tar.gz", samples)]

raw_df = data.frame()
for ( s in samples ){
  id = str_match(s, ".*_(.*)\\.matrix")[, 2]
  raw_df = rbind ( raw_df , data.frame ( pid=id, file=s))
}




```


























